language: c
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - python3
compiler:
  - gcc-4.9
script:
  echo "cc gcc-4.9" > test.conf;
  echo "cflags -Wall -std=c99 -I~/src/" >> test.conf;
  make PY=python3 test
