language: c
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - python3
compiler:
  - gcc-4.9
script:
  cat << EOF > test.conf
  cc gcc-4.9
  cflags -Wall -std=c99 -I~/src/
  EOF
  make PY=python3 test
